### ISSUE TITLE
Mostrar mensaje cuando existan errores de tipos

### ISSUE THREAD

**Issue by marcelouva** [marcelodarroyo/progenv#1]
Sería interesante que cuando se ejecutan los procedimientos se pudiera mostrar algún mensaje si existe  algún  error de tipos o de cantidad de parámetros. Por ej.  cuando ponemos  dibujarLinea(0,0,400,A) mostrar un mensaje que diga algo como "El procedimiento espera un número  o algo por el estilo".  Me parece que estaría bueno para ir agregando la noción de tipo de datos.
abz!

**Comment by marcelodarroyo** [comment]
Esto requiere parsear javascript. Es posible hacerlo usando [Esprima](https://github.com/ariya/esprima). Creo que sería de una gran utilidad pero hay que planearlo como un gran TO DO...
La otra es usar typescript, pero es difícil usarlo en el browser sin server.

**Comment by marcelodarroyo** [comment]
Pensándolo mejor, es aún más difícil, porque deberíamos agregar anotaciones, ya que Javascript es un lenguaje no tipado por lo que en estos casos "todo compila". El programa de abajo es un programa válido:
function f() {
   return 2;
}
f(5);
